name: solicitud_empleo_app
description: "Aplicación para la gestión de solicitudes de empleo"
publish_to: 'none' # Evita la publicación accidental a pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0' #  Ajusta el rango del SDK (más flexible)

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.0 #   Asegúrate de tener la última versión
  google_fonts: ^6.1.0 #  Asegúrate de tener la última versión

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1 #  Asegúrate de tener la última versión

flutter:
  uses-material-design: true
  assets:
    - assets/ #   Simplifica la ruta (si todos los assets están aquí)
  # fonts: #  Si vas a usar fuentes, descomenta esto y agrega las rutas
  #   - family: Poppins
  #     fonts:
  #       - asset: assets/fonts/Poppins-Regular.ttf
  #       - asset: assets/fonts/Poppins-Bold.ttf
  #         weight: 700